# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11390a10953ee769b194af3459b7e60abffbdaa3e52fefabd9f9dadf55cc0937f7e189209531343a0f6be3085a94dbe8cea64cd2e392f8a39cca297b93558b65

test:
  secret_key_base: c8487a5994069e69757dfaac2ef1360924255bc34f39d03e3a0c603d12373899ca7e989c65e66b3268e4b81d63b2c159c97291e80a3ec7c4d8f8b10a1f7f32b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
